-- ============================================================
-- Migration: Community Feed v2
-- ============================================================
-- Run after migration_community_post_images.sql. Safe to re-run.
--
-- Scope decisions:
-- - Posts now support up to 3 images (image_urls text[]).
--   The legacy image_url column is left intact — ~170 existing rows
--   use it and there is zero data-migration risk. The client reads both.
-- - Replies can carry 1 image (image_url text). Replies are closer to
--   conversational chat, so 1 is appropriate; multi-image reply support
--   is out of scope and would raise the same cascading-cleanup questions
--   as reply reactions (deliberately left for later).
-- - New DOUBT post type added to the CHECK constraint.
-- - No new storage bucket needed — community-post-images already accepts
--   the right MIME types and file size; the same per-user path convention
--   (${userId}/${uuid}.ext) is reused for extra images.
-- - Rate limits (community_posts_guard / community_replies_guard) are
--   unchanged — they count rows, not images.
-- ============================================================

-- ---------- 1. community_posts: multi-image array ----------
alter table community_posts add column if not exists image_urls text[] not null default '{}';

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'community_posts_image_urls_len') then
    alter table community_posts
      add constraint community_posts_image_urls_len check (
        array_length(image_urls, 1) is null or array_length(image_urls, 1) <= 3
      ) not valid;
  end if;
end $$;

-- ---------- 2. community_posts: DOUBT post type ----------
-- Drop the existing CHECK constraint on `type`, then re-add it with
-- DOUBT included. The constraint name is auto-generated by Postgres as
-- community_posts_type_check — verify with \d community_posts if needed.
alter table community_posts drop constraint if exists community_posts_type_check;
alter table community_posts add constraint community_posts_type_check
  check (type in ('CHECK_IN', 'PROGRESS', 'QUESTION', 'TIP', 'MILESTONE', 'DOUBT'));

-- ---------- 3. community_replies: single image ----------
alter table community_replies add column if not exists image_url text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'community_replies_image_url_len') then
    alter table community_replies
      add constraint community_replies_image_url_len check (
        image_url is null or char_length(image_url) <= 600
      ) not valid;
  end if;
end $$;
